Repository nerdguyahmad/qord, pull requests merged in 2022-03, with the labels that each got.

#9 Add support for “greater than” and “lower than” operators and to roles.
  qord/models/roles.py
Labels: t: feature, p: low, s: pending

#13 Add alpha identifier to current version.
  qord/project_info.py
  setup.py
Labels: t: branch sync

#14 Implement ratelimits handling
  CONTRIBUTING.MD
  qord/core/ratelimits.py
  qord/core/rest.py
  qord/core/routes.py
Labels: t: feature, p: high, s: testing needed
